version: '3.8'
services:
  db:
    image: postgres:11.5-alpine
    container_name: postgres-11.5
    restart: always
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
      - POSTGRES_DB=nest_blog
    ports:
      - '5432:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  db:
    driver: local